name: CultivaTech CI/CD

on:
  push:
    branches:
      - LuSilva-dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push api-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest

      - name: Build and push auth-backend
        uses: docker/build-push-action@v5
        with:
          context: ./Autentication-Users/Back-End
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-backend:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/auth-backend:latest
      
      - name: Build and push auth-frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Autentication-Users/Front-End
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-frontend:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/auth-frontend:latest

      - name: Build and push config-server
        uses: docker/build-push-action@v5
        with:
          context: ./Config-Server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/config-server:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/config-server:latest

      - name: Build and push discovery-server
        uses: docker/build-push-action@v5
        with:
          context: ./discovery-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/discovery-server:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/discovery-server:latest

      - name: Build and push farm-production
        uses: docker/build-push-action@v5
        with:
          context: ./farm-production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/farm-production:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/farm-production:latest
      
      - name: Build and push property-service
        uses: docker/build-push-action@v5
        with:
          context: ./Property-Service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/property-service:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/property-service:latest

  deploy:
    runs-on: self-hosted
    needs: build_and_push
    environment: Production
    
    steps:
    - name: Deploy on Self-Hosted Runner
      # Não é mais necessário usar uma action de SSH, pois o runner está na máquina
      # Você pode executar os comandos diretamente.
      run: |
        cd 'C:\Users\55319\cultivatech'
        git pull origin LuSilva-dev
        
        # Login usando as variáveis do ambiente do runner
        printf "%s" "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
        
        # Agora o pull e o up funcionarão
        docker-compose -f docker-compose.prod.yml pull
        docker-compose -f docker-compose.prod.yml up -d --remove-orphans
        docker image prune -f